### ISSUE TITLE
GIF: error in DGifGetImageDesc()

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.io.image#13]
https://travis-ci.org/conda-forge/bob.io.image-feedstock/builds/135645811
I will investigate more and update this issue. ~~This happens on osx only.~~ It happens on osx and Linux.
```
ERROR: bob.io.image.test.test_cpp_interface

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/bob/io/image/test.py", line 77, in test_cpp_interface

    _test_io(tmpdir)

RuntimeError: _test_io: C++ exception caught: 'GIF: error in DGifGetImageDesc().'

```

**Comment by anjos** [comment]
We have a mac system available so, running the nightlies should incur in the same bug? Or is it dependent on the libgif version?

**Comment by 183amir** [comment]
I am looking at the first two builds; the same version of `libgif` is used In both only different dependencies are:
```patch
--- a
+++ b
@@ -7,11 +7,12 @@
     giflib:        5.1.2-0           conda-forge
     hdf5:          1.8.17-0          conda-forge
     icu:           56.1-2            conda-forge
-    jpeg:          9b-0              conda-forge
+    jbig:          2.1-0             defaults   
+    jpeg:          8d-1              defaults   
     libblitz:      0.10-0            conda-forge
     libgcc:        4.8.5-1           defaults   
     libpng:        1.6.21-1          conda-forge
-    libtiff:       4.0.6-4           conda-forge
+    libtiff:       4.0.6-2           defaults   
     mkl:           11.3.3-0          defaults   
     numpy:         1.11.0-py27_1     defaults   
     openssl:       1.0.2h-1          defaults   
@@ -23,5 +24,5 @@
     sqlite:        3.13.0-0          conda-forge
     tk:            8.5.19-0          conda-forge
     wheel:         0.29.0-py27_0     defaults   
-    xz:            5.0.5-1           conda-forge
+    xz:            5.2.2-0           defaults   
     zlib:          1.2.8-3           conda-forge
```

**Comment by 183amir** [comment]
This is a random error. It may be because the file is not flushed after writing: https://github.com/bioidiap/bob.io.image/blob/master/bob/io/image/main.cpp#L71

**Comment by 183amir** [comment]
This issue keep re-appearing: https://circleci.com/gh/conda-forge/bob-feedstock/15

**Comment by tiagofrepereira2012** [comment]
Well, happened again (https://travis-ci.org/conda-forge/bob.io.image-feedstock/jobs/149664724).
What is the best course of action?
